"""empty message

Revision ID: 299c568f63ab
Revises: 3d1f1a238abd
Create Date: 2018-09-28 13:03:01.414752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299c568f63ab'
down_revision = '3d1f1a238abd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'comment')
    # ### end Alembic commands ###
