"""empty message

Revision ID: 3d1f1a238abd
Revises: 980f96f23f7c
Create Date: 2018-09-27 16:54:01.666527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d1f1a238abd'
down_revision = '980f96f23f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('like', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'like')
    # ### end Alembic commands ###
