"""empty message

Revision ID: 980f96f23f7c
Revises: 57cc9a7b34fa
Create Date: 2018-09-21 17:44:14.052872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '980f96f23f7c'
down_revision = '57cc9a7b34fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'age')
    # ### end Alembic commands ###
